### ISSUE TITLE
Vivint verification code not working

### ISSUE THREAD

**Issue by philvilar** [hoobs-org/sidecars#12]
Since the newest update on Vivint via HOOBS, I cannot seem to log in to my account and get passed submitting my verification code. One I type it in, it simply reloads the page and is asking me to resubmit the code again. I know several other people are having the same issues here:

[https://github.com/balansse/homebridge-vivint/issues/129](url)

Any help would be appreciated!

**Comment by mcpeach** [comment]
Just got my hoobs box today, mostly for this functionality, and I'm running into this issue as well.

**Comment by CzKing94** [comment]
This is not working for me either. Anytime I put my PIN number to verify — it will not accept and continues to refresh. Please fix this issue.

**Comment by ronster22** [comment]
Same issue here...

**Comment by ronster22** [comment]
@mkellsy any idea on how to fix this?

**Comment by askovi** [comment]
I just pushed a fix for the MFA issue. I had to republish the sidecar so to get the updated one please do the following:

1. Uninstall Vivint plugin / delete Vivint bridge
2. Go to the top right menu > Hub Settings
3. Click the Clear Cache button. Then click OK. Then click Apply
4. Reinstall Vivint plugin
5. Link account as usual

I don't have a Vivint account to test with so if you run into any issue please let me know.

**Comment by mcpeach** [comment]
> I just pushed a fix for the MFA issue. I had to republish the sidecar so to get the updated one please do the following:
> 
> 1. Uninstall Vivint plugin / delete Vivint bridge
> 2. Go to the top right menu > Hub Settings
> 3. Click the Clear Cache button. Then click OK. Then click Apply
> 4. Reinstall Vivint plugin
> 5. Link account as usual
> 
> I don't have a Vivint account to test with so if you run into any issue please let me know.

mmm....seems it's more broken now.   Now, when I enter in the email/password, I don't get taken to the screen to verify via code, it just reloads the login page.  Before it would go to the code page, and then the code page would just re-load after entering.

**Comment by askovi** [comment]
> > I just pushed a fix for the MFA issue. I had to republish the sidecar so to get the updated one please do the following:
> > 
> > 1. Uninstall Vivint plugin / delete Vivint bridge
> > 2. Go to the top right menu > Hub Settings
> > 3. Click the Clear Cache button. Then click OK. Then click Apply
> > 4. Reinstall Vivint plugin
> > 5. Link account as usual
> > 
> > I don't have a Vivint account to test with so if you run into any issue please let me know.
> 
> mmm....seems it's more broken now. Now, when I enter in the email/password, I don't get taken to the screen to verify via code, it just reloads the login page. Before it would go to the code page, and then the code page would just re-load after entering.

@mcpeach can you send me an email to ovi@hoobs.com I need some debug information to be able to test.

**Comment by ronster22** [comment]
I re-installed the plugin and it still shows version 1.8.5...

**Comment by askovi** [comment]
@ronster22 the plugin version is the same. What changed is the sidecar inside the plugin

Send me an email if you can help with debug info at ovi@hoobs.com

**Comment by ronster22** [comment]
@askovi Sent you an email with the debug of my failed attempt..

**Comment by askovi** [comment]
Thank you to @mcpeach and @ronster22 for the assistance with the debug via email. 

A new version of the Vivint sidecar has been released which fixes all the issue and adds error handling and display. 
If you already have the Vivint plugin installed, make sure you follow this guide to get the new sidecar:

1. Uninstall Vivint plugin / delete Vivint bridge
2. Go to the top right menu > Hub Settings
3. Click the Clear Cache button. Then click OK. Then click Apply
4. Reinstall Vivint plugin
5. Link account as usual

**Comment by ronster22** [comment]
Ok finally got it to work. Took a few attempts and reboots, but its back online.

Thanks again @askovi !
